/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SDAV.Vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Ryzen
 */
public class VistaArranquePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form ArranquePrincipal
     */
    public VistaArranquePrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btSalir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jpInicairSesion = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_Cedu = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        bt_Ingresar = new javax.swing.JButton();
        txtError = new javax.swing.JLabel();
        jbRegistarse = new javax.swing.JButton();
        txt_Correo = new javax.swing.JTextField();
        jpRegistrarse = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        apellE = new javax.swing.JTextField();
        nomE = new javax.swing.JTextField();
        CeduE = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btncancE = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        EmailE = new javax.swing.JTextField();
        btnaceptE = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        sueldE = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        etiquetacorreo = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        EmailEAd = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setTitle("WELCOME");
        setPreferredSize(new java.awt.Dimension(900, 650));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(1, 187, 246));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 650));

        jPanel2.setBackground(new java.awt.Color(9, 122, 253));

        btSalir.setBackground(new java.awt.Color(147, 191, 242));
        btSalir.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        btSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SDAV/Vista/Iconos/icons8_exit_30px.png"))); // NOI18N
        btSalir.setText("SALIR");
        btSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(147, 191, 242));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel3.setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        jLabel1.setText("INICIAR SESIÓN");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SDAV/Vista/Iconos/icons8_user_80px.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/SDAV/Vista/Iconos/icons8_carpark_128px_4.png"))); // NOI18N
        jLabel2.setOpaque(true);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SDAV/Vista/Iconos/businessapplication_accept_ok_male_man_you_negocio_2311.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SDAV/Vista/Iconos/icons8_password_64px.png"))); // NOI18N

        txt_Cedu.setBackground(new java.awt.Color(240, 240, 240));
        txt_Cedu.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        txt_Cedu.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Cedu.setBorder(null);
        txt_Cedu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CeduActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel5.setText("Correo");

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel6.setText("Cédula");

        jSeparator1.setForeground(new java.awt.Color(9, 122, 253));

        jSeparator2.setForeground(new java.awt.Color(9, 122, 253));

        bt_Ingresar.setBackground(new java.awt.Color(9, 122, 253));
        bt_Ingresar.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        bt_Ingresar.setForeground(new java.awt.Color(255, 255, 255));
        bt_Ingresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SDAV/Vista/Iconos/icons8_play_32px.png"))); // NOI18N
        bt_Ingresar.setText("INGRESAR");
        bt_Ingresar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_Ingresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_IngresarActionPerformed(evt);
            }
        });

        txtError.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        txtError.setForeground(new java.awt.Color(255, 0, 0));

        jbRegistarse.setBackground(new java.awt.Color(255, 255, 255));
        jbRegistarse.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jbRegistarse.setForeground(new java.awt.Color(204, 0, 0));
        jbRegistarse.setText("Registrarse/aqui");
        jbRegistarse.setBorder(null);
        jbRegistarse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txt_Correo.setBackground(new java.awt.Color(240, 240, 240));
        txt_Correo.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        txt_Correo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Correo.setBorder(null);
        txt_Correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CorreoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpInicairSesionLayout = new javax.swing.GroupLayout(jpInicairSesion);
        jpInicairSesion.setLayout(jpInicairSesionLayout);
        jpInicairSesionLayout.setHorizontalGroup(
            jpInicairSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpInicairSesionLayout.createSequentialGroup()
                .addGroup(jpInicairSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpInicairSesionLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel1))
                    .addGroup(jpInicairSesionLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabel2))
                    .addGroup(jpInicairSesionLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel3)
                        .addGroup(jpInicairSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpInicairSesionLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jpInicairSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jpInicairSesionLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_Correo, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jpInicairSesionLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtError, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpInicairSesionLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jpInicairSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpInicairSesionLayout.createSequentialGroup()
                                .addComponent(jbRegistarse, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80)
                                .addComponent(bt_Ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpInicairSesionLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGroup(jpInicairSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpInicairSesionLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jpInicairSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jpInicairSesionLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_Cedu, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(10, 10, 10))
        );
        jpInicairSesionLayout.setVerticalGroup(
            jpInicairSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpInicairSesionLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(jpInicairSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpInicairSesionLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3))
                    .addGroup(jpInicairSesionLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Correo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(jpInicairSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jpInicairSesionLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Cedu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(jpInicairSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpInicairSesionLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jbRegistarse, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bt_Ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(txtError, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.add(jpInicairSesion, "card2");

        jLabel11.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel11.setText("Cédula:");

        apellE.setBackground(new java.awt.Color(240, 240, 240));
        apellE.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        apellE.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        apellE.setBorder(null);

        nomE.setBackground(new java.awt.Color(240, 240, 240));
        nomE.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        nomE.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nomE.setBorder(null);

        CeduE.setBackground(new java.awt.Color(240, 240, 240));
        CeduE.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        CeduE.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CeduE.setBorder(null);

        jPanel6.setBackground(new java.awt.Color(9, 122, 253));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SDAV/Vista/Iconos/icons8_user_80px.png"))); // NOI18N

        btncancE.setBackground(new java.awt.Color(9, 122, 253));
        btncancE.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btncancE.setForeground(new java.awt.Color(255, 255, 255));
        btncancE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SDAV/Vista/Iconos/CANCELACION.png"))); // NOI18N
        btncancE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncancE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btncancE, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131)
                .addComponent(jLabel12)
                .addContainerGap(180, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btncancE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jLabel13.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel13.setText("Sueldo:");

        jLabel14.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel14.setText("Nombre:");

        jLabel15.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel15.setText("Apellidos:");

        jLabel16.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel16.setText("E-mail:");
        jLabel16.setToolTipText("");

        EmailE.setBackground(new java.awt.Color(240, 240, 240));
        EmailE.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        EmailE.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EmailE.setBorder(null);

        btnaceptE.setBackground(new java.awt.Color(0, 204, 51));
        btnaceptE.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnaceptE.setText("REGISTRAR");
        btnaceptE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jSeparator5.setBackground(new java.awt.Color(0, 102, 255));

        sueldE.setBackground(new java.awt.Color(240, 240, 240));
        sueldE.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        sueldE.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sueldE.setBorder(null);

        jSeparator6.setBackground(new java.awt.Color(0, 102, 255));

        jSeparator7.setBackground(new java.awt.Color(0, 102, 255));

        jSeparator8.setBackground(new java.awt.Color(0, 102, 255));

        jSeparator9.setBackground(new java.awt.Color(0, 102, 255));

        etiquetacorreo.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        etiquetacorreo.setForeground(new java.awt.Color(255, 0, 0));

        jLabel17.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel17.setText("E-mail:");
        jLabel17.setToolTipText("");

        EmailEAd.setBackground(new java.awt.Color(240, 240, 240));
        EmailEAd.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        EmailEAd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EmailEAd.setBorder(null);

        jSeparator10.setBackground(new java.awt.Color(0, 102, 255));

        jLabel18.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("INGRESAR  UN CORREO ELECTRÓNICO DE ALGÚN OTRO ADMINISTRADOR");

        javax.swing.GroupLayout jpRegistrarseLayout = new javax.swing.GroupLayout(jpRegistrarse);
        jpRegistrarse.setLayout(jpRegistrarseLayout);
        jpRegistrarseLayout.setHorizontalGroup(
            jpRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jpRegistrarseLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(CeduE, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jpRegistrarseLayout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jpRegistrarseLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(nomE, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jpRegistrarseLayout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jpRegistrarseLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addGroup(jpRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(apellE, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jpRegistrarseLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(sueldE, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jpRegistrarseLayout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jpRegistrarseLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(EmailE, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(etiquetacorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jpRegistrarseLayout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jpRegistrarseLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jpRegistrarseLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jpRegistrarseLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel17)
                .addGap(26, 26, 26)
                .addGroup(jpRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EmailEAd, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpRegistrarseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnaceptE, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
        );
        jpRegistrarseLayout.setVerticalGroup(
            jpRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRegistrarseLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jpRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpRegistrarseLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel11))
                    .addComponent(CeduE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jpRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpRegistrarseLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel14))
                    .addComponent(nomE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jpRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpRegistrarseLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel15))
                    .addGroup(jpRegistrarseLayout.createSequentialGroup()
                        .addComponent(apellE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(jpRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpRegistrarseLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel13))
                    .addComponent(sueldE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jpRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpRegistrarseLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel16))
                    .addComponent(EmailE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetacorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jpRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpRegistrarseLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel17))
                    .addGroup(jpRegistrarseLayout.createSequentialGroup()
                        .addComponent(EmailEAd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnaceptE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.add(jpRegistrarse, "card3");

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SDAV/Vista/Iconos/logo4.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(147, 191, 242));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        jLabel7.setText("SISTEMA DE ADMINITRACIÓN VEHICULAR");

        jLabel8.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 60)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(9, 122, 253));
        jLabel8.setText("SDAV");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SDAV/Vista/Iconos/Captura.PNG"))); // NOI18N

        jTextPane1.setEditable(false);
        jTextPane1.setBorder(null);
        jTextPane1.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jTextPane1.setText("El parqueadero Ricaurte ofrece servicios \nde estacionamiento para autos de todo \n     tipo, brindando en todo momento \n     seguridad y resguardo vehicular.");
        jTextPane1.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextPane1.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(44, 44, 44))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 943, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_IngresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_IngresarActionPerformed

    private void btSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btSalirActionPerformed

    private void txt_CeduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CeduActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CeduActionPerformed

    private void btncancEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncancEActionPerformed

    private void txt_CorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CorreoActionPerformed

    public JButton getBt_Ingresar() {
        return bt_Ingresar;
    }

    public void setBt_Ingresar(JButton bt_Ingresar) {
        this.bt_Ingresar = bt_Ingresar;
    }

    public JTextField getTxt_Cedu() {
        return txt_Cedu;
    }

    public void setTxt_Cedu(JTextField txt_Cedu) {
        this.txt_Cedu = txt_Cedu;
    }

    public JTextField getTxt_Correo() {
        return txt_Correo;
    }

    public void setTxt_Correo(JTextField txt_Correo) {
        this.txt_Correo = txt_Correo;
    }

   

    public JTextField getTxt_User() {
        return txt_Cedu;
    }

    public void setTxt_User(JTextField txt_User) {
        this.txt_Cedu = txt_User;
    }

    public JButton getBtSalir() {
        return btSalir;
    }

    public void setBtSalir(JButton btSalir) {
        this.btSalir = btSalir;
    }

    public JLabel getTxtError() {
        return txtError;
    }

    public void setTxtError(JLabel txtError) {
        this.txtError = txtError;
    }

    public JTextField getCeduE() {
        return CeduE;
    }

    public void setCeduE(JTextField CeduE) {
        this.CeduE = CeduE;
    }

    public JTextField getEmailE() {
        return EmailE;
    }

    public void setEmailE(JTextField EmailE) {
        this.EmailE = EmailE;
    }

    public JTextField getEmailEAd() {
        return EmailEAd;
    }

    public void setEmailEAd(JTextField EmailEAd) {
        this.EmailEAd = EmailEAd;
    }

    public JTextField getApellE() {
        return apellE;
    }

    public void setApellE(JTextField apellE) {
        this.apellE = apellE;
    }

    public JLabel getEtiquetacorreo() {
        return etiquetacorreo;
    }

    public void setEtiquetacorreo(JLabel etiquetacorreo) {
        this.etiquetacorreo = etiquetacorreo;
    }

    public JButton getJbRegistarse() {
        return jbRegistarse;
    }

    public void setJbRegistarse(JButton jbRegistarse) {
        this.jbRegistarse = jbRegistarse;
    }

    
    public JButton getBtnaceptE() {
        return btnaceptE;
    }

    public void setBtnaceptE(JButton btnaceptE) {
        this.btnaceptE = btnaceptE;
    }

    public JButton getBtncancE() {
        return btncancE;
    }

    public void setBtncancE(JButton btncancE) {
        this.btncancE = btncancE;
    }

    public JPanel getJpInicairSesion() {
        return jpInicairSesion;
    }

    public void setJpInicairSesion(JPanel jpInicairSesion) {
        this.jpInicairSesion = jpInicairSesion;
    }

    public JPanel getJpRegistrarse() {
        return jpRegistrarse;
    }

    public void setJpRegistrarse(JPanel jpRegistrarse) {
        this.jpRegistrarse = jpRegistrarse;
    }

    public JTextField getNomE() {
        return nomE;
    }

    public void setNomE(JTextField nomE) {
        this.nomE = nomE;
    }

    public JTextField getSueldE() {
        return sueldE;
    }

    public void setSueldE(JTextField sueldE) {
        this.sueldE = sueldE;
    }

    



    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CeduE;
    private javax.swing.JTextField EmailE;
    private javax.swing.JTextField EmailEAd;
    private javax.swing.JTextField apellE;
    private javax.swing.JButton btSalir;
    private javax.swing.JButton bt_Ingresar;
    private javax.swing.JButton btnaceptE;
    private javax.swing.JButton btncancE;
    private javax.swing.JLabel etiquetacorreo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JButton jbRegistarse;
    private javax.swing.JPanel jpInicairSesion;
    private javax.swing.JPanel jpRegistrarse;
    private javax.swing.JTextField nomE;
    private javax.swing.JTextField sueldE;
    private javax.swing.JLabel txtError;
    private javax.swing.JTextField txt_Cedu;
    private javax.swing.JTextField txt_Correo;
    // End of variables declaration//GEN-END:variables
}
