/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SDAV.Vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Bryans
 */
public class VistaVehiculo extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaVehiculo
     */
    public VistaVehiculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CrearVehiculo = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        txtplaca = new javax.swing.JTextField();
        txtmarca = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtcolor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnaceptV = new javax.swing.JButton();
        btncancV = new javax.swing.JButton();
        btnExamnV = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblFoto = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jcPropietario = new javax.swing.JComboBox<>();
        jctipoV = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabVehiculos = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtBuscarV = new javax.swing.JTextField();
        btnCrearV = new javax.swing.JButton();
        btnEditarV = new javax.swing.JButton();
        btnEliminarV = new javax.swing.JButton();
        btnListarV = new javax.swing.JButton();
        btnImprimirV = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel8.setText("Foto:");

        txtplaca.setBackground(new java.awt.Color(240, 240, 240));
        txtplaca.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        txtplaca.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtplaca.setBorder(null);

        txtmarca.setBackground(new java.awt.Color(240, 240, 240));
        txtmarca.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        txtmarca.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtmarca.setBorder(null);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel2.setText("Placa:");

        txtcolor.setBackground(new java.awt.Color(240, 240, 240));
        txtcolor.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        txtcolor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtcolor.setBorder(null);

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel3.setText("Propietario:");

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel4.setText("Marca:");

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel6.setText("Color:");

        btnaceptV.setBackground(new java.awt.Color(0, 204, 51));
        btnaceptV.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnaceptV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SDAV/Vista/Iconos/Add.png"))); // NOI18N
        btnaceptV.setText("Crear");

        btncancV.setBackground(new java.awt.Color(0, 204, 153));
        btncancV.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btncancV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SDAV/Vista/Iconos/CANCELACION.png"))); // NOI18N
        btncancV.setText("Cancelar");
        btncancV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancVActionPerformed(evt);
            }
        });

        btnExamnV.setBackground(new java.awt.Color(0, 204, 153));
        btnExamnV.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnExamnV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SDAV/Vista/Iconos/Login.png"))); // NOI18N
        btnExamnV.setText("Examinar");
        btnExamnV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExamnVActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(9, 122, 253));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SDAV/Vista/Iconos/icons8_car_top_view_48px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(168, 168, 168))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(11, 11, 11)
                .addComponent(jLabel10))
        );

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel7.setText("Tipo VehÍculo:");

        lblFoto.setToolTipText("");
        lblFoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jSeparator2.setForeground(new java.awt.Color(0, 102, 255));

        jSeparator3.setForeground(new java.awt.Color(0, 102, 255));

        jSeparator4.setForeground(new java.awt.Color(0, 102, 255));

        jSeparator5.setForeground(new java.awt.Color(0, 102, 255));

        jSeparator6.setForeground(new java.awt.Color(0, 102, 255));

        jcPropietario.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jcPropietario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR" }));

        jctipoV.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jctipoV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "PESADO", "LIVIANO" }));

        javax.swing.GroupLayout CrearVehiculoLayout = new javax.swing.GroupLayout(CrearVehiculo.getContentPane());
        CrearVehiculo.getContentPane().setLayout(CrearVehiculoLayout);
        CrearVehiculoLayout.setHorizontalGroup(
            CrearVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearVehiculoLayout.createSequentialGroup()
                .addGroup(CrearVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CrearVehiculoLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel2)
                        .addGap(29, 29, 29)
                        .addGroup(CrearVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CrearVehiculoLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(txtplaca, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(98, 98, 98)
                        .addComponent(jLabel8))
                    .addGroup(CrearVehiculoLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(CrearVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CrearVehiculoLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(9, 9, 9)
                                .addComponent(jcPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CrearVehiculoLayout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CrearVehiculoLayout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(jLabel4)
                                .addGap(30, 30, 30)
                                .addComponent(txtmarca, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CrearVehiculoLayout.createSequentialGroup()
                                .addGap(160, 160, 160)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CrearVehiculoLayout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(jLabel6)
                                .addGap(30, 30, 30)
                                .addComponent(txtcolor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CrearVehiculoLayout.createSequentialGroup()
                                .addGap(160, 160, 160)
                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(63, 63, 63)
                        .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CrearVehiculoLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel7)
                        .addGap(29, 29, 29)
                        .addGroup(CrearVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jctipoV, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addComponent(btnExamnV))
                    .addGroup(CrearVehiculoLayout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(btnaceptV, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btncancV, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        CrearVehiculoLayout.setVerticalGroup(
            CrearVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearVehiculoLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(CrearVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CrearVehiculoLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addGroup(CrearVehiculoLayout.createSequentialGroup()
                        .addComponent(txtplaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CrearVehiculoLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel8)))
                .addGap(2, 2, 2)
                .addGroup(CrearVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CrearVehiculoLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(CrearVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jcPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addGroup(CrearVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addGroup(CrearVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CrearVehiculoLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel6))
                            .addComponent(txtcolor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(CrearVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CrearVehiculoLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel7))
                    .addGroup(CrearVehiculoLayout.createSequentialGroup()
                        .addComponent(jctipoV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CrearVehiculoLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(btnExamnV, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(CrearVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnaceptV, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncancV, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("VEHÍCULOS");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/SDAV/Vista/Iconos/icons8_carpool_16px.png"))); // NOI18N

        tabVehiculos.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        tabVehiculos.setForeground(new java.awt.Color(102, 102, 102));
        tabVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Placa", "Propietario", "Marca", "Color", "Tipo", "Foto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabVehiculos);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(9, 122, 253));
        jPanel3.setPreferredSize(new java.awt.Dimension(898, 65));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SDAV/Vista/Iconos/icons8_search_40px_3.png"))); // NOI18N
        jLabel5.setText("Buscar:");

        txtBuscarV.setToolTipText("BUSCAR");
        txtBuscarV.setBorder(null);
        txtBuscarV.setMinimumSize(new java.awt.Dimension(6, 27));
        txtBuscarV.setPreferredSize(new java.awt.Dimension(6, 27));

        btnCrearV.setBackground(new java.awt.Color(147, 191, 242));
        btnCrearV.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCrearV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SDAV/Vista/Iconos/icons8_add_40px.png"))); // NOI18N
        btnCrearV.setToolTipText("NUEVO");
        btnCrearV.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCrearV.setMaximumSize(new java.awt.Dimension(47, 47));
        btnCrearV.setMinimumSize(new java.awt.Dimension(47, 47));
        btnCrearV.setPreferredSize(new java.awt.Dimension(47, 47));

        btnEditarV.setBackground(new java.awt.Color(147, 191, 242));
        btnEditarV.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEditarV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SDAV/Vista/Iconos/icons8_edit_40px_2.png"))); // NOI18N
        btnEditarV.setToolTipText("EDITAR");
        btnEditarV.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEditarV.setMaximumSize(new java.awt.Dimension(47, 47));
        btnEditarV.setMinimumSize(new java.awt.Dimension(47, 47));
        btnEditarV.setPreferredSize(new java.awt.Dimension(47, 47));

        btnEliminarV.setBackground(new java.awt.Color(147, 191, 242));
        btnEliminarV.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEliminarV.setForeground(new java.awt.Color(147, 191, 242));
        btnEliminarV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SDAV/Vista/Iconos/icons8_delete_40px.png"))); // NOI18N
        btnEliminarV.setToolTipText("ELIMINAR");
        btnEliminarV.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEliminarV.setMaximumSize(new java.awt.Dimension(47, 47));
        btnEliminarV.setMinimumSize(new java.awt.Dimension(47, 47));
        btnEliminarV.setPreferredSize(new java.awt.Dimension(47, 47));

        btnListarV.setBackground(new java.awt.Color(147, 191, 242));
        btnListarV.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnListarV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SDAV/Vista/Iconos/icons8_list_40px.png"))); // NOI18N
        btnListarV.setToolTipText("LISTAR");
        btnListarV.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnImprimirV.setBackground(new java.awt.Color(147, 191, 242));
        btnImprimirV.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnImprimirV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SDAV/Vista/Iconos/icons8_print_40px.png"))); // NOI18N
        btnImprimirV.setToolTipText("IMPRIMIR");
        btnImprimirV.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscarV, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnCrearV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditarV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 230, Short.MAX_VALUE)
                .addComponent(btnListarV, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnImprimirV)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCrearV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminarV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditarV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtBuscarV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnImprimirV, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnListarV, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setPreferredSize(new java.awt.Dimension(893, 50));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SDAV/Vista/Iconos/logo4.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 545, Short.MAX_VALUE)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncancVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncancVActionPerformed

    private void btnExamnVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExamnVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExamnVActionPerformed

    public JTextField getTxtmarca() {
        return txtmarca;
    }

    public void setTxtmarca(JTextField txtmarca) {
        this.txtmarca = txtmarca;
    }

    public JComboBox<String> getJctipoV() {
        return jctipoV;
    }

    public void setJctipoV(JComboBox<String> jctipoV) {
        this.jctipoV = jctipoV;
    }

    

    public JLabel getLblFoto() {
        return lblFoto;
    }

    public void setLblFoto(JLabel lblFoto) {
        this.lblFoto = lblFoto;
    }

    /**
     * @param args the command line arguments
     */

    public JDialog getCrearVehiculo() {
        return CrearVehiculo;
    }

    public void setCrearVehiculo(JDialog CrearVehiculo) {
        this.CrearVehiculo = CrearVehiculo;
    }

    public JButton getBtnCrearV() {
        return btnCrearV;
    }

    public void setBtnCrearV(JButton btnCrearV) {
        this.btnCrearV = btnCrearV;
    }

    public JButton getBtnEditarV() {
        return btnEditarV;
    }

    public void setBtnEditarV(JButton btnEditarV) {
        this.btnEditarV = btnEditarV;
    }

    public JButton getBtnEliminarV() {
        return btnEliminarV;
    }

    public void setBtnEliminarV(JButton btnEliminarV) {
        this.btnEliminarV = btnEliminarV;
    }

    public JButton getBtnExamnV() {
        return btnExamnV;
    }

    public void setBtnExamnV(JButton btnExamnV) {
        this.btnExamnV = btnExamnV;
    }

    public JButton getBtnImprimirV() {
        return btnImprimirV;
    }

    public void setBtnImprimirV(JButton btnImprimirV) {
        this.btnImprimirV = btnImprimirV;
    }

    public JButton getBtnListarV() {
        return btnListarV;
    }

    public void setBtnListarV(JButton btnListarV) {
        this.btnListarV = btnListarV;
    }

    public JButton getBtnaceptV() {
        return btnaceptV;
    }

    public void setBtnaceptV(JButton btnaceptV) {
        this.btnaceptV = btnaceptV;
    }

    public JButton getBtncancV() {
        return btncancV;
    }

    public void setBtncancV(JButton btncancV) {
        this.btncancV = btncancV;
    }

   

    public JTable getTabVehiculos() {
        return tabVehiculos;
    }

    public void setTabVehiculos(JTable tabVehiculos) {
        this.tabVehiculos = tabVehiculos;
    }

    public JTextField getTxtBuscarV() {
        return txtBuscarV;
    }

    public void setTxtBuscarV(JTextField txtBuscarV) {
        this.txtBuscarV = txtBuscarV;
    }

    public JComboBox<String> getJcPropietario() {
        return jcPropietario;
    }

    public void setJcPropietario(JComboBox<String> jcPropietario) {
        this.jcPropietario = jcPropietario;
    }

   

    public JTextField getTxtcolor() {
        return txtcolor;
    }

    public void setTxtcolor(JTextField txtcolor) {
        this.txtcolor = txtcolor;
    }

    public JTextField getTxtmodelo() {
        return txtmarca;
    }

    public void setTxtmodelo(JTextField txtmodelo) {
        this.txtmarca = txtmodelo;
    }

    public JTextField getTxtplaca() {
        return txtplaca;
    }

    public void setTxtplaca(JTextField txtplaca) {
        this.txtplaca = txtplaca;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog CrearVehiculo;
    private javax.swing.JButton btnCrearV;
    private javax.swing.JButton btnEditarV;
    private javax.swing.JButton btnEliminarV;
    private javax.swing.JButton btnExamnV;
    private javax.swing.JButton btnImprimirV;
    private javax.swing.JButton btnListarV;
    private javax.swing.JButton btnaceptV;
    private javax.swing.JButton btncancV;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JComboBox<String> jcPropietario;
    private javax.swing.JComboBox<String> jctipoV;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JTable tabVehiculos;
    private javax.swing.JTextField txtBuscarV;
    private javax.swing.JTextField txtcolor;
    private javax.swing.JTextField txtmarca;
    private javax.swing.JTextField txtplaca;
    // End of variables declaration//GEN-END:variables
}
