/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SDAV.Vista;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Bryans
 */
public class VistaEmpleado extends javax.swing.JInternalFrame{

    /**
     * Creates new form VistaEmpleado
     */
    public VistaEmpleado() {
        initComponents();
    }

    public JTextField getCeduE() {
        return CeduE;
    }

    public void setCeduE(JTextField CeduE) {
        this.CeduE = CeduE;
    }

    public JDialog getCrearEmpleado() {
        return CrearEmpleado;
    }

    public void setCrearEmpleado(JDialog CrearEmpleado) {
        this.CrearEmpleado = CrearEmpleado;
    }

    public JTextField getEmailE() {
        return EmailE;
    }

    public void setEmailE(JTextField EmailE) {
        this.EmailE = EmailE;
    }

    public JComboBox<String> getJbCargo() {
        return jbCargo;
    }

    public void setJbCargo(JComboBox<String> jbCargo) {
        this.jbCargo = jbCargo;
    }

    public JTextField getApellE() {
        return apellE;
    }

    public void setApellE(JTextField apellE) {
        this.apellE = apellE;
    }

    public JButton getBtnCrearE() {
        return btnCrearE;
    }

    public void setBtnCrearE(JButton btnCrearE) {
        this.btnCrearE = btnCrearE;
    }

    public JButton getBtnEditarE() {
        return btnEditarE;
    }

    public void setBtnEditarE(JButton btnEditarE) {
        this.btnEditarE = btnEditarE;
    }

    public JLabel getEtiquetacorreo() {
        return etiquetacorreo;
    }

    public void setEtiquetacorreo(JLabel etiquetacorreo) {
        this.etiquetacorreo = etiquetacorreo;
    }

    public JButton getBtnEliminarE() {
        return btnEliminarE;
    }

    public void setBtnEliminarE(JButton btnEliminarE) {
        this.btnEliminarE = btnEliminarE;
    }

    public JButton getBtnImprimirE() {
        return btnImprimirE;
    }

    public void setBtnImprimirE(JButton btnImprimirE) {
        this.btnImprimirE = btnImprimirE;
    }

    public JButton getBtnListarE() {
        return btnListarE;
    }

    public void setBtnListarE(JButton btnListarE) {
        this.btnListarE = btnListarE;
    }

    public JButton getBtnaceptE() {
        return btnaceptE;
    }

    public void setBtnaceptE(JButton btnaceptE) {
        this.btnaceptE = btnaceptE;
    }

    public JButton getBtncancE() {
        return btncancE;
    }

    public void setBtncancE(JButton btncancE) {
        this.btncancE = btncancE;
    }



    public JTextField getNomE() {
        return nomE;
    }

    public void setNomE(JTextField nomE) {
        this.nomE = nomE;
    }

    public JTextField getSueldE() {
        return sueldE;
    }

    public void setSueldE(JTextField sueldE) {
        this.sueldE = sueldE;
    }

    public JTable getTabEmpleados() {
        return tabEmpleados;
    }

    public void setTabEmpleados(JTable tabEmpleados) {
        this.tabEmpleados = tabEmpleados;
    }

    public JTextField getTxtBuscarE() {
        return txtBuscarE;
    }

    public void setTxtBuscarE(JTextField txtBuscarE) {
        this.txtBuscarE = txtBuscarE;
    }

    public JTextField getTxtmin() {
        return txtmin;
    }

    public void setTxtmin(JTextField txtmin) {
        this.txtmin = txtmin;
    }

    public JTextField getTxtpmax() {
        return txtpmax;
    }

    public void setTxtpmax(JTextField txtpmax) {
        this.txtpmax = txtpmax;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CrearEmpleado = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        EmailE = new javax.swing.JTextField();
        btnaceptE = new javax.swing.JButton();
        btncancE = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        CeduE = new javax.swing.JTextField();
        nomE = new javax.swing.JTextField();
        apellE = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        sueldE = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jbCargo = new javax.swing.JComboBox<>();
        etiquetacorreo = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabEmpleados = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtBuscarE = new javax.swing.JTextField();
        btnCrearE = new javax.swing.JButton();
        btnEditarE = new javax.swing.JButton();
        btnEliminarE = new javax.swing.JButton();
        btnListarE = new javax.swing.JButton();
        btnImprimirE = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        txtpmax = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtmin = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jcMin = new javax.swing.JCheckBox();
        jcMax = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();

        CrearEmpleado.setResizable(false);

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel4.setText("Apellidos:");

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel6.setText("Sueldo:");

        EmailE.setBackground(new java.awt.Color(240, 240, 240));
        EmailE.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        EmailE.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EmailE.setBorder(null);

        btnaceptE.setBackground(new java.awt.Color(0, 204, 51));
        btnaceptE.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnaceptE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SDAV/Vista/Iconos/Add.png"))); // NOI18N
        btnaceptE.setText("Crear");

        btncancE.setBackground(new java.awt.Color(0, 204, 153));
        btncancE.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btncancE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SDAV/Vista/Iconos/CANCELACION.png"))); // NOI18N
        btncancE.setText("Cancelar");
        btncancE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancEActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel8.setText("E-mail:");
        jLabel8.setToolTipText("");

        CeduE.setBackground(new java.awt.Color(240, 240, 240));
        CeduE.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        CeduE.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CeduE.setBorder(null);

        nomE.setBackground(new java.awt.Color(240, 240, 240));
        nomE.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        nomE.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nomE.setBorder(null);

        apellE.setBackground(new java.awt.Color(240, 240, 240));
        apellE.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        apellE.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        apellE.setBorder(null);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel2.setText("Cédula:");

        sueldE.setBackground(new java.awt.Color(240, 240, 240));
        sueldE.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        sueldE.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sueldE.setBorder(null);

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel5.setText("Cargo:");

        jPanel4.setBackground(new java.awt.Color(9, 122, 253));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SDAV/Vista/Iconos/icons8_user_30px_1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(209, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(201, 201, 201))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSeparator2.setBackground(new java.awt.Color(0, 102, 255));

        jSeparator3.setBackground(new java.awt.Color(0, 102, 255));

        jSeparator4.setBackground(new java.awt.Color(0, 102, 255));

        jSeparator5.setBackground(new java.awt.Color(0, 102, 255));

        jSeparator6.setBackground(new java.awt.Color(0, 102, 255));

        jSeparator7.setBackground(new java.awt.Color(0, 102, 255));

        jbCargo.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jbCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE" }));

        etiquetacorreo.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        etiquetacorreo.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout CrearEmpleadoLayout = new javax.swing.GroupLayout(CrearEmpleado.getContentPane());
        CrearEmpleado.getContentPane().setLayout(CrearEmpleadoLayout);
        CrearEmpleadoLayout.setHorizontalGroup(
            CrearEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearEmpleadoLayout.createSequentialGroup()
                .addGroup(CrearEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CrearEmpleadoLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(CrearEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CeduE, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(CrearEmpleadoLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CrearEmpleadoLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CrearEmpleadoLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(btnaceptE, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btncancE, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CrearEmpleadoLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addGroup(CrearEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sueldE, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(CrearEmpleadoLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addGroup(CrearEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CrearEmpleadoLayout.createSequentialGroup()
                                .addComponent(EmailE, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(etiquetacorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(CrearEmpleadoLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(CrearEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(CrearEmpleadoLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(nomE, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(CrearEmpleadoLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(CrearEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(apellE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CrearEmpleadoLayout.setVerticalGroup(
            CrearEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearEmpleadoLayout.createSequentialGroup()
                .addGroup(CrearEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(CrearEmpleadoLayout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(CeduE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addGap(0, 0, 0)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(CrearEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CrearEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nomE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(1, 1, 1)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CrearEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CrearEmpleadoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4))
                    .addGroup(CrearEmpleadoLayout.createSequentialGroup()
                        .addComponent(apellE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CrearEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(CrearEmpleadoLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel8))
                    .addGroup(CrearEmpleadoLayout.createSequentialGroup()
                        .addComponent(sueldE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(EmailE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(etiquetacorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(CrearEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnaceptE, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncancE, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setBackground(new java.awt.Color(9, 122, 253));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("EMPLEADOS");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/SDAV/Vista/Iconos/icons8_employee_16px_1.png"))); // NOI18N
        setInheritsPopupMenu(true);

        tabEmpleados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tabEmpleados.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        tabEmpleados.setForeground(new java.awt.Color(102, 102, 102));
        tabEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cédula", "Cargo", "Nombre", "Apellido", "E-mail", "Sueldo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabEmpleados.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        tabEmpleados.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(tabEmpleados);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(9, 122, 253));
        jPanel3.setPreferredSize(new java.awt.Dimension(898, 65));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SDAV/Vista/Iconos/icons8_find_user_male_40px.png"))); // NOI18N
        jLabel1.setText("Buscar:");

        txtBuscarE.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        txtBuscarE.setToolTipText("BUSCAR");
        txtBuscarE.setBorder(null);
        txtBuscarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarEActionPerformed(evt);
            }
        });

        btnCrearE.setBackground(new java.awt.Color(147, 191, 242));
        btnCrearE.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCrearE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SDAV/Vista/Iconos/icons8_add_user_male_40px.png"))); // NOI18N
        btnCrearE.setToolTipText("NUEVO");
        btnCrearE.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCrearE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearEActionPerformed(evt);
            }
        });

        btnEditarE.setBackground(new java.awt.Color(147, 191, 242));
        btnEditarE.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEditarE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SDAV/Vista/Iconos/icons8_registration_40px.png"))); // NOI18N
        btnEditarE.setToolTipText("EDITAR");
        btnEditarE.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnEliminarE.setBackground(new java.awt.Color(147, 191, 242));
        btnEliminarE.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEliminarE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SDAV/Vista/Iconos/icons8_denied_40px.png"))); // NOI18N
        btnEliminarE.setToolTipText("ELIMINAR");
        btnEliminarE.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnListarE.setBackground(new java.awt.Color(147, 191, 242));
        btnListarE.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnListarE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SDAV/Vista/Iconos/icons8_list_40px.png"))); // NOI18N
        btnListarE.setToolTipText("LISTAR");
        btnListarE.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnImprimirE.setBackground(new java.awt.Color(147, 191, 242));
        btnImprimirE.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnImprimirE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SDAV/Vista/Iconos/icons8_print_40px.png"))); // NOI18N
        btnImprimirE.setToolTipText("IMPRIMIR");
        btnImprimirE.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        txtpmax.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        txtpmax.setToolTipText("");
        txtpmax.setBorder(null);

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Salario Max");

        txtmin.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        txtmin.setBorder(null);

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Salario Min");

        jcMin.setBackground(new java.awt.Color(9, 122, 253));
        jcMin.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N

        jcMax.setBackground(new java.awt.Color(9, 122, 253));
        jcMax.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jcMax.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscarE, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCrearE, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditarE, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcMax, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jcMin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtpmax)
                    .addComponent(txtmin, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnListarE, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnImprimirE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEliminarE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditarE, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCrearE, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtBuscarE, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnListarE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnImprimirE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcMax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtpmax)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcMin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtmin, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setPreferredSize(new java.awt.Dimension(824, 50));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SDAV/Vista/Iconos/logo4.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 611, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarEActionPerformed

    private void btnCrearEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearEActionPerformed

    private void btncancEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncancEActionPerformed

    /**
     * @param args the command line arguments
     */

    public JCheckBox getJcMax() {
        return jcMax;
    }

    public void setJcMax(JCheckBox jcMax) {
        this.jcMax = jcMax;
    }

    public JCheckBox getJcMin() {
        return jcMin;
    }

    public void setJcMin(JCheckBox jcMin) {
        this.jcMin = jcMin;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CeduE;
    private javax.swing.JDialog CrearEmpleado;
    private javax.swing.JTextField EmailE;
    private javax.swing.JTextField apellE;
    private javax.swing.JButton btnCrearE;
    private javax.swing.JButton btnEditarE;
    private javax.swing.JButton btnEliminarE;
    private javax.swing.JButton btnImprimirE;
    private javax.swing.JButton btnListarE;
    private javax.swing.JButton btnaceptE;
    private javax.swing.JButton btncancE;
    private javax.swing.JLabel etiquetacorreo;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JComboBox<String> jbCargo;
    private javax.swing.JCheckBox jcMax;
    private javax.swing.JCheckBox jcMin;
    private javax.swing.JTextField nomE;
    private javax.swing.JTextField sueldE;
    private javax.swing.JTable tabEmpleados;
    private javax.swing.JTextField txtBuscarE;
    private javax.swing.JTextField txtmin;
    private javax.swing.JTextField txtpmax;
    // End of variables declaration//GEN-END:variables
}
