/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SDAV.Vista;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author USUARIO
 */
public class VistaZonaEstacionamiento extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaZonaEstacionamiento
     */
    public VistaZonaEstacionamiento() {
        initComponents();
    }

    public JButton getB_crearzona1() {
        return b_crearzona1;
    }

    public void setB_crearzona1(JButton b_crearzona1) {
        this.b_crearzona1 = b_crearzona1;
    }

    public JButton getB_editarzona1() {
        return b_editarzona1;
    }

    public void setB_editarzona1(JButton b_editarzona1) {
        this.b_editarzona1 = b_editarzona1;
    }

    public JButton getB_eliminarzona1() {
        return b_eliminarzona1;
    }

    public void setB_eliminarzona1(JButton b_eliminarzona1) {
        this.b_eliminarzona1 = b_eliminarzona1;
    }

    public JButton getB_imprimirzona() {
        return b_imprimirzona;
    }

    public void setB_imprimirzona(JButton b_imprimirzona) {
        this.b_imprimirzona = b_imprimirzona;
    }

    public JButton getB_listarzona1() {
        return b_listarzona1;
    }

    public void setB_listarzona1(JButton b_listarzona1) {
        this.b_listarzona1 = b_listarzona1;
    }

    public JTable getTablazona() {
        return tablazona;
    }

    public void setTablazona(JTable tablazona) {
        this.tablazona = tablazona;
    }

   
    public JTextField getTxtbuscar() {
        return txtbuscar;
    }

    public void setTxtbuscar(JTextField txtbuscar) {
        this.txtbuscar = txtbuscar;
    }

    public JComboBox<String> getComboBoxid_tarifa() {
        return ComboBoxid_tarifa;
    }

    public void setComboBoxid_tarifa(JComboBox<String> ComboBoxid_tarifa) {
        this.ComboBoxid_tarifa = ComboBoxid_tarifa;
    }

    public JButton getBaceptar() {
        return baceptar;
    }


    public void setBaceptar(JButton baceptar) {
        this.baceptar = baceptar;
    }

    public JButton getBcancelar() {
        return bcancelar;
    }

    public void setBcancelar(JButton bcancelar) {
        this.bcancelar = bcancelar;
    }

    public JButton getBotonexaminar() {
        return botonexaminar;
    }

    public void setBotonexaminar(JButton botonexaminar) {
        this.botonexaminar = botonexaminar;
    }

    public JDialog getDlgZona() {
        return dlgZona;
    }

    public void setDlgZona(JDialog dlgZona) {
        this.dlgZona = dlgZona;
    }

    public JLabel getLabelfoto() {
        return labelfoto;
    }

    public void setLabelfoto(JLabel labelfoto) {
        this.labelfoto = labelfoto;
    }

    public ButtonGroup getButtonEstado() {
        return buttonEstado;
    }

    public void setButtonEstado(ButtonGroup buttonEstado) {
        this.buttonEstado = buttonEstado;
    }

    public JRadioButton getRb_a() {
        return rb_a;
    }

    public void setRb_a(JRadioButton rb_a) {
        this.rb_a = rb_a;
    }

    public JRadioButton getRb_d() {
        return rb_d;
    }

    public void setRb_d(JRadioButton rb_d) {
        this.rb_d = rb_d;
    }



    public JTextField getTextid_zona() {
        return textid_zona;
    }

    public void setTextid_zona(JTextField textid_zona) {
        this.textid_zona = textid_zona;
    }

    public JTextField getTxtnombrezona() {
        return txtnombrezona;
    }

    public void setTxtnombrezona(JTextField txtnombrezona) {
        this.txtnombrezona = txtnombrezona;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgZona = new javax.swing.JDialog();
        jPanel7 = new javax.swing.JPanel();
        labelfoto = new javax.swing.JLabel();
        botonexaminar = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        ComboBoxid_tarifa = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtnombrezona = new javax.swing.JTextField();
        textid_zona = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        rb_a = new javax.swing.JRadioButton();
        rb_d = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        baceptar = new javax.swing.JButton();
        bcancelar = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        buttonEstado = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        b_crearzona1 = new javax.swing.JButton();
        b_editarzona1 = new javax.swing.JButton();
        b_listarzona1 = new javax.swing.JButton();
        b_eliminarzona1 = new javax.swing.JButton();
        b_imprimirzona = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtbuscar = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablazona = new javax.swing.JTable();

        dlgZona.setBackground(new java.awt.Color(0, 153, 255));
        dlgZona.setForeground(new java.awt.Color(204, 255, 204));
        dlgZona.setResizable(false);

        labelfoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        botonexaminar.setBackground(new java.awt.Color(153, 204, 255));
        botonexaminar.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        botonexaminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SDAV/Vista/Iconos/folder.png"))); // NOI18N
        botonexaminar.setText("EXAMINAR");
        botonexaminar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jSeparator3.setForeground(new java.awt.Color(35, 130, 178));

        jSeparator4.setForeground(new java.awt.Color(35, 130, 178));

        ComboBoxid_tarifa.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        ComboBoxid_tarifa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE" }));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel5.setText("ID:");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel6.setText("NOMBRE:");

        txtnombrezona.setBackground(new java.awt.Color(240, 240, 240));
        txtnombrezona.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        txtnombrezona.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtnombrezona.setBorder(null);

        textid_zona.setBackground(new java.awt.Color(240, 240, 240));
        textid_zona.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        textid_zona.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textid_zona.setBorder(null);

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel7.setText("TARIFA:");

        buttonEstado.add(rb_a);
        rb_a.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        rb_a.setText("LIBRE");

        buttonEstado.add(rb_d);
        rb_d.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        rb_d.setText("OCUPADO");

        jLabel12.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel12.setText("ESTADO:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonexaminar, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(textid_zona, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(txtnombrezona, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(ComboBoxid_tarifa, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rb_d)
                                    .addComponent(rb_a))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addGap(90, 90, 90)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(60, 60, 60)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addGap(50, 50, 50)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addGap(30, 30, 30)
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(textid_zona, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addGap(40, 40, 40)
                                    .addComponent(txtnombrezona, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addGap(90, 90, 90)
                                    .addComponent(ComboBoxid_tarifa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addGap(70, 70, 70)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rb_a)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(rb_d)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(labelfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonexaminar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        baceptar.setBackground(new java.awt.Color(0, 153, 0));
        baceptar.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        baceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SDAV/Vista/Iconos/añadir compra.png"))); // NOI18N
        baceptar.setText("ACEPTAR");
        baceptar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0), 2));
        jPanel8.add(baceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 121, -1));

        bcancelar.setBackground(new java.awt.Color(255, 51, 51));
        bcancelar.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        bcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SDAV/Vista/Iconos/CANCELACION.png"))); // NOI18N
        bcancelar.setText("CANCELAR");
        bcancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51), 2));
        bcancelar.setBorderPainted(false);
        jPanel8.add(bcancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 126, -1));

        jPanel10.setBackground(new java.awt.Color(9, 122, 253));

        jLabel13.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SDAV/Vista/Iconos/icons8_outdoor_parking_80px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(jLabel13)
                .addContainerGap(247, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout dlgZonaLayout = new javax.swing.GroupLayout(dlgZona.getContentPane());
        dlgZona.getContentPane().setLayout(dlgZonaLayout);
        dlgZonaLayout.setHorizontalGroup(
            dlgZonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgZonaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(dlgZonaLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        dlgZonaLayout.setVerticalGroup(
            dlgZonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgZonaLayout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setBackground(new java.awt.Color(102, 102, 102));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("ZONAS");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/SDAV/Vista/Iconos/icons8_paid_parking_16px.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(9, 122, 253));
        jPanel1.setPreferredSize(new java.awt.Dimension(942, 70));

        b_crearzona1.setBackground(new java.awt.Color(147, 191, 242));
        b_crearzona1.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        b_crearzona1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SDAV/Vista/Iconos/icons8_add_40px.png"))); // NOI18N
        b_crearzona1.setToolTipText("NUEVO");
        b_crearzona1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        b_editarzona1.setBackground(new java.awt.Color(147, 191, 242));
        b_editarzona1.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        b_editarzona1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SDAV/Vista/Iconos/icons8_edit_40px_2.png"))); // NOI18N
        b_editarzona1.setToolTipText("EDITAR");
        b_editarzona1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        b_listarzona1.setBackground(new java.awt.Color(147, 191, 242));
        b_listarzona1.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        b_listarzona1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SDAV/Vista/Iconos/icons8_list_40px.png"))); // NOI18N
        b_listarzona1.setToolTipText("LISTAR");
        b_listarzona1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        b_eliminarzona1.setBackground(new java.awt.Color(147, 191, 242));
        b_eliminarzona1.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        b_eliminarzona1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SDAV/Vista/Iconos/icons8_delete_40px.png"))); // NOI18N
        b_eliminarzona1.setToolTipText("ELIMINAR");
        b_eliminarzona1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b_eliminarzona1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_eliminarzona1ActionPerformed(evt);
            }
        });

        b_imprimirzona.setBackground(new java.awt.Color(147, 191, 242));
        b_imprimirzona.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        b_imprimirzona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SDAV/Vista/Iconos/icons8_print_40px.png"))); // NOI18N
        b_imprimirzona.setToolTipText("IMPRIMIR");
        b_imprimirzona.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Buscar:");

        txtbuscar.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        txtbuscar.setToolTipText("BUSCAR");
        txtbuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_crearzona1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_editarzona1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_eliminarzona1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 301, Short.MAX_VALUE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(b_listarzona1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_imprimirzona, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(b_listarzona1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b_imprimirzona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b_crearzona1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b_editarzona1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(17, 17, 17)
                            .addComponent(jLabel17))
                        .addComponent(b_eliminarzona1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(6, 6, 6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setPreferredSize(new java.awt.Dimension(942, 50));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SDAV/Vista/Iconos/logo4.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 685, Short.MAX_VALUE)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        tablazona.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51), 2));
        tablazona.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        tablazona.setForeground(new java.awt.Color(102, 102, 102));
        tablazona.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Foto", "Zona", "Nombre", "Tarifa", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablazona.setGridColor(new java.awt.Color(151, 153, 73));
        tablazona.setSelectionBackground(new java.awt.Color(153, 255, 153));
        tablazona.setSelectionForeground(new java.awt.Color(0, 0, 51));
        jScrollPane1.setViewportView(tablazona);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_eliminarzona1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_eliminarzona1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_eliminarzona1ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxid_tarifa;
    private javax.swing.JButton b_crearzona1;
    private javax.swing.JButton b_editarzona1;
    private javax.swing.JButton b_eliminarzona1;
    private javax.swing.JButton b_imprimirzona;
    private javax.swing.JButton b_listarzona1;
    private javax.swing.JButton baceptar;
    private javax.swing.JButton bcancelar;
    private javax.swing.JButton botonexaminar;
    private javax.swing.ButtonGroup buttonEstado;
    private javax.swing.JDialog dlgZona;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel labelfoto;
    private javax.swing.JRadioButton rb_a;
    private javax.swing.JRadioButton rb_d;
    private javax.swing.JTable tablazona;
    private javax.swing.JTextField textid_zona;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JTextField txtnombrezona;
    // End of variables declaration//GEN-END:variables
}
