/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SDAV.Vista;

import javax.swing.JButton;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Ryzen
 */
public class VistaFactura extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaFactura
     */
    public VistaFactura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Servicio = new javax.swing.JInternalFrame();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_Final = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        txtDIA1 = new javax.swing.JLabel();
        txtHora1 = new javax.swing.JLabel();
        btTerminar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabFactura = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtBuscarE = new javax.swing.JTextField();
        btnEliminarF = new javax.swing.JButton();
        btnListarF = new javax.swing.JButton();
        btnImprimirF = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnListarF1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();

        Servicio.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Servicio.setClosable(true);
        Servicio.setIconifiable(true);
        Servicio.setMaximizable(true);
        Servicio.setResizable(true);
        Servicio.setTitle("SERVICIO ACTUAL");
        Servicio.setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/SDAV/Vista/Iconos/icons8_service_16px.png"))); // NOI18N
        Servicio.setVisible(true);

        jPanel10.setBackground(new java.awt.Color(1, 187, 246));

        tb_Final.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        tb_Final.setForeground(new java.awt.Color(102, 102, 102));
        tb_Final.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "TICKET", "FOTO", "PLACA", "CEDULA", "NOMBRE", "HORA DE ENTRADA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tb_Final);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 852, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
        );

        Servicio.getContentPane().add(jPanel10, java.awt.BorderLayout.CENTER);

        jPanel9.setBackground(new java.awt.Color(1, 187, 246));
        jPanel9.setPreferredSize(new java.awt.Dimension(200, 653));
        jPanel9.setRequestFocusEnabled(false);

        txtDIA1.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        txtDIA1.setForeground(new java.awt.Color(255, 255, 255));
        txtDIA1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtDIA1.setText("DD/MM/YYYY");

        txtHora1.setBackground(new java.awt.Color(255, 255, 255));
        txtHora1.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        txtHora1.setForeground(new java.awt.Color(255, 255, 255));
        txtHora1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtHora1.setText("HH/MM/SS");

        btTerminar.setBackground(new java.awt.Color(204, 0, 0));
        btTerminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SDAV/Vista/Iconos/icons8_end_200px.png"))); // NOI18N
        btTerminar.setToolTipText("NUEVO TICKET");
        btTerminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btTerminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FINALIZAR SEVICIO");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtDIA1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addComponent(txtHora1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btTerminar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(25, 25, 25))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addComponent(txtDIA1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHora1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 365, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addComponent(btTerminar, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Servicio.getContentPane().add(jPanel9, java.awt.BorderLayout.LINE_END);

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("FACTURAS");
        setToolTipText("");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/SDAV/Vista/Iconos/icons8_invoice_16px.png"))); // NOI18N

        tabFactura.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tabFactura.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        tabFactura.setForeground(new java.awt.Color(102, 102, 102));
        tabFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Factura", "Cédula", "Tikets", "Fecha de Emición", "Sub Total", "Hora de Intreso", "Hora de Salida", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabFactura.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        jScrollPane1.setViewportView(tabFactura);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(9, 122, 253));
        jPanel3.setPreferredSize(new java.awt.Dimension(898, 65));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Buscar:");

        txtBuscarE.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        txtBuscarE.setToolTipText("BUSCAR");
        txtBuscarE.setBorder(null);
        txtBuscarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarEActionPerformed(evt);
            }
        });

        btnEliminarF.setBackground(new java.awt.Color(147, 191, 242));
        btnEliminarF.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEliminarF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SDAV/Vista/Iconos/icons8_delete_40px.png"))); // NOI18N
        btnEliminarF.setToolTipText("ELIMINAR");
        btnEliminarF.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnListarF.setBackground(new java.awt.Color(147, 191, 242));
        btnListarF.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnListarF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SDAV/Vista/Iconos/icons8_list_40px.png"))); // NOI18N
        btnListarF.setToolTipText("LISTAR");
        btnListarF.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnImprimirF.setBackground(new java.awt.Color(147, 191, 242));
        btnImprimirF.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnImprimirF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SDAV/Vista/Iconos/icons8_print_40px.png"))); // NOI18N
        btnImprimirF.setToolTipText("FACTURIZAR");
        btnImprimirF.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnListarF1.setBackground(new java.awt.Color(147, 191, 242));
        btnListarF1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnListarF1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SDAV/Vista/Iconos/icons8_invoice_64px.png"))); // NOI18N
        btnListarF1.setToolTipText("IMPRIMIR UNA FACTURA");
        btnListarF1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscarE, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnListarF1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 397, Short.MAX_VALUE)
                .addComponent(btnListarF, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnImprimirF)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnListarF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnImprimirF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBuscarE, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnListarF1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(btnEliminarF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18))))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setPreferredSize(new java.awt.Dimension(824, 50));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SDAV/Vista/Iconos/logo4.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 611, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarEActionPerformed

    public JButton getBtnEliminarF() {
        return btnEliminarF;
    }

    public void setBtnEliminarF(JButton btnEliminarF) {
        this.btnEliminarF = btnEliminarF;
    }

    public JButton getBtnImprimirF() {
        return btnImprimirF;
    }

    public void setBtnImprimirF(JButton btnImprimirF) {
        this.btnImprimirF = btnImprimirF;
    }

    public JButton getBtnListarF() {
        return btnListarF;
    }

    public void setBtnListarF(JButton btnListarF) {
        this.btnListarF = btnListarF;
    }

    public JTable getTabFactura() {
        return tabFactura;
    }

    public void setTabFactura(JTable tabFactura) {
        this.tabFactura = tabFactura;
    }

    public JTextField getTxtBuscarE() {
        return txtBuscarE;
    }

    public void setTxtBuscarE(JTextField txtBuscarE) {
        this.txtBuscarE = txtBuscarE;
    }

    public JInternalFrame getServicio() {
        return Servicio;
    }

    public void setServicio(JInternalFrame Servicio) {
        this.Servicio = Servicio;
    }

    

    public JButton getBtTerminar() {
        return btTerminar;
    }

    public void setBtTerminar(JButton btTerminar) {
        this.btTerminar = btTerminar;
    }

    public JTable getTb_Final() {
        return tb_Final;
    }

    public void setTb_Final(JTable tb_Final) {
        this.tb_Final = tb_Final;
    }

    public JLabel getTxtDIA1() {
        return txtDIA1;
    }

    public void setTxtDIA1(JLabel txtDIA1) {
        this.txtDIA1 = txtDIA1;
    }

    public JLabel getTxtHora1() {
        return txtHora1;
    }

    public void setTxtHora1(JLabel txtHora1) {
        this.txtHora1 = txtHora1;
    }

    public JButton getBtnListarF1() {
        return btnListarF1;
    }

    public void setBtnListarF1(JButton btnListarF1) {
        this.btnListarF1 = btnListarF1;
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame Servicio;
    private javax.swing.JButton btTerminar;
    private javax.swing.JButton btnEliminarF;
    private javax.swing.JButton btnImprimirF;
    private javax.swing.JButton btnListarF;
    private javax.swing.JButton btnListarF1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tabFactura;
    private javax.swing.JTable tb_Final;
    private javax.swing.JTextField txtBuscarE;
    private javax.swing.JLabel txtDIA1;
    private javax.swing.JLabel txtHora1;
    // End of variables declaration//GEN-END:variables
}
