/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SDAV.Vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Ryzen
 */
public class VistaNuevoTicket extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaNuevoTicket
     */
    public VistaNuevoTicket() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel11 = new javax.swing.JPanel();
        jpLCliente = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        joLAuto = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jpLTicket = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jpLConfirmacion = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jpCliente2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        direccion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tel = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        apell = new javax.swing.JTextField();
        nom = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jpAuto2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtplaca = new javax.swing.JTextField();
        txtmarca = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtcolor = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnExamnV = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lblFoto = new javax.swing.JLabel();
        jctipoV = new javax.swing.JComboBox<>();
        jpTicket2 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        textid_ticket = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        ComboBoxid_zona = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        labelfecha = new javax.swing.JLabel();
        labelhora = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jpConfirmacion2 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        lch = new javax.swing.JLabel();
        lcc1 = new javax.swing.JLabel();
        lcp1 = new javax.swing.JLabel();
        lct = new javax.swing.JLabel();
        lcf = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        btCancel = new javax.swing.JButton();
        btNext = new javax.swing.JButton();
        btBack = new javax.swing.JButton();
        txtNumpanel = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SERVICIO-NUEVO TICKET");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/SDAV/Vista/Iconos/icons8_service_16px.png"))); // NOI18N

        jPanel11.setBackground(new java.awt.Color(9, 122, 253));
        jPanel11.setMinimumSize(new java.awt.Dimension(127, 100));
        jPanel11.setPreferredSize(new java.awt.Dimension(300, 492));

        jpLCliente.setBackground(new java.awt.Color(1, 187, 246));

        jLabel9.setBackground(new java.awt.Color(1, 187, 246));
        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SDAV/Vista/Iconos/icons8_user_40px.png"))); // NOI18N
        jLabel9.setText("CLIENTE");

        javax.swing.GroupLayout jpLClienteLayout = new javax.swing.GroupLayout(jpLCliente);
        jpLCliente.setLayout(jpLClienteLayout);
        jpLClienteLayout.setHorizontalGroup(
            jpLClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLClienteLayout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpLClienteLayout.setVerticalGroup(
            jpLClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpLClienteLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        joLAuto.setBackground(new java.awt.Color(9, 122, 253));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SDAV/Vista/Iconos/icons8_car_top_view_48px.png"))); // NOI18N
        jLabel10.setText("AUTO");

        javax.swing.GroupLayout joLAutoLayout = new javax.swing.GroupLayout(joLAuto);
        joLAuto.setLayout(joLAutoLayout);
        joLAutoLayout.setHorizontalGroup(
            joLAutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(joLAutoLayout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        joLAutoLayout.setVerticalGroup(
            joLAutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(joLAutoLayout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        jpLTicket.setBackground(new java.awt.Color(9, 122, 253));

        jLabel11.setBackground(new java.awt.Color(9, 122, 253));
        jLabel11.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SDAV/Vista/Iconos/icons8_ticket_48px.png"))); // NOI18N
        jLabel11.setText("TICKET");

        javax.swing.GroupLayout jpLTicketLayout = new javax.swing.GroupLayout(jpLTicket);
        jpLTicket.setLayout(jpLTicketLayout);
        jpLTicketLayout.setHorizontalGroup(
            jpLTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLTicketLayout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpLTicketLayout.setVerticalGroup(
            jpLTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpLTicketLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpLConfirmacion.setBackground(new java.awt.Color(9, 122, 253));

        jLabel12.setBackground(new java.awt.Color(9, 122, 253));
        jLabel12.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SDAV/Vista/Iconos/icons8_checkmark_64px_1.png"))); // NOI18N
        jLabel12.setText("CONFIRMACIÓN");

        javax.swing.GroupLayout jpLConfirmacionLayout = new javax.swing.GroupLayout(jpLConfirmacion);
        jpLConfirmacion.setLayout(jpLConfirmacionLayout);
        jpLConfirmacionLayout.setHorizontalGroup(
            jpLConfirmacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 302, Short.MAX_VALUE)
            .addGroup(jpLConfirmacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpLConfirmacionLayout.createSequentialGroup()
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jpLConfirmacionLayout.setVerticalGroup(
            jpLConfirmacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jpLConfirmacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpLConfirmacionLayout.createSequentialGroup()
                    .addGap(2, 2, 2)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SDAV/Vista/Iconos/logo4.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpLCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jpLConfirmacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jpLTicket, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(joLAuto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(jpLCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(joLAuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpLTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpLConfirmacion, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel11, java.awt.BorderLayout.LINE_START);

        jPanel13.setLayout(new java.awt.CardLayout());

        jpCliente2.setBackground(new java.awt.Color(1, 187, 246));
        jpCliente2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Teléfono:");

        jPanel4.setBackground(new java.awt.Color(9, 122, 253));

        jLabel13.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SDAV/Vista/Iconos/icons8_user_80px.png"))); // NOI18N
        jLabel13.setText("DATOS DEL CLIENTE ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jLabel13)
                .addContainerGap(162, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        direccion.setBackground(new java.awt.Color(1, 187, 246));
        direccion.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        direccion.setForeground(new java.awt.Color(255, 255, 255));
        direccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        direccion.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Apellidos:");

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre:");

        tel.setBackground(new java.awt.Color(1, 187, 246));
        tel.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        tel.setForeground(new java.awt.Color(255, 255, 255));
        tel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cédula:");

        apell.setBackground(new java.awt.Color(1, 187, 246));
        apell.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        apell.setForeground(new java.awt.Color(255, 255, 255));
        apell.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        apell.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        nom.setBackground(new java.awt.Color(1, 187, 246));
        nom.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        nom.setForeground(new java.awt.Color(255, 255, 255));
        nom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nom.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        id.setBackground(new java.awt.Color(1, 187, 246));
        id.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        id.setForeground(new java.awt.Color(255, 255, 255));
        id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        id.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Dirección:");

        javax.swing.GroupLayout jpCliente2Layout = new javax.swing.GroupLayout(jpCliente2);
        jpCliente2.setLayout(jpCliente2Layout);
        jpCliente2Layout.setHorizontalGroup(
            jpCliente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpCliente2Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(jpCliente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jpCliente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apell, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tel, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpCliente2Layout.setVerticalGroup(
            jpCliente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCliente2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(jpCliente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jpCliente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(33, 33, 33)
                .addGroup(jpCliente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(apell, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(31, 31, 31)
                .addGroup(jpCliente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(30, 30, 30)
                .addGroup(jpCliente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)))
        );

        jPanel13.add(jpCliente2, "card2");

        jpAuto2.setBackground(new java.awt.Color(1, 187, 246));
        jpAuto2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel14.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Foto:");

        txtplaca.setBackground(new java.awt.Color(1, 187, 246));
        txtplaca.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        txtplaca.setForeground(new java.awt.Color(255, 255, 255));
        txtplaca.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtplaca.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtmarca.setBackground(new java.awt.Color(1, 187, 246));
        txtmarca.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        txtmarca.setForeground(new java.awt.Color(255, 255, 255));
        txtmarca.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtmarca.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Placa:");

        txtcolor.setBackground(new java.awt.Color(1, 187, 246));
        txtcolor.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        txtcolor.setForeground(new java.awt.Color(255, 255, 255));
        txtcolor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtcolor.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel15.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Marca:");

        jLabel16.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Color:");

        btnExamnV.setBackground(new java.awt.Color(1, 187, 246));
        btnExamnV.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        btnExamnV.setForeground(new java.awt.Color(255, 255, 255));
        btnExamnV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SDAV/Vista/Iconos/Login.png"))); // NOI18N
        btnExamnV.setText("Examinar");
        btnExamnV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExamnVActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(9, 122, 253));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SDAV/Vista/Iconos/icons8_public_transportation_80px.png"))); // NOI18N
        jLabel18.setText("DATOS DE AUTO");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(168, 168, 168))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17))
        );

        jLabel19.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Tipo Vehículo:");

        lblFoto.setBackground(new java.awt.Color(255, 255, 255));
        lblFoto.setToolTipText("");
        lblFoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jctipoV.setBackground(new java.awt.Color(1, 187, 246));
        jctipoV.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jctipoV.setForeground(new java.awt.Color(255, 255, 255));
        jctipoV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "PESADO", "LIVIANO" }));

        javax.swing.GroupLayout jpAuto2Layout = new javax.swing.GroupLayout(jpAuto2);
        jpAuto2.setLayout(jpAuto2Layout);
        jpAuto2Layout.setHorizontalGroup(
            jpAuto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpAuto2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jpAuto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(jpAuto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtmarca)
                    .addComponent(txtplaca)
                    .addComponent(txtcolor)
                    .addComponent(jctipoV, 0, 211, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jpAuto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAuto2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(86, 86, 86))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAuto2Layout.createSequentialGroup()
                        .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAuto2Layout.createSequentialGroup()
                        .addComponent(btnExamnV)
                        .addGap(29, 29, 29))))
        );
        jpAuto2Layout.setVerticalGroup(
            jpAuto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAuto2Layout.createSequentialGroup()
                .addGroup(jpAuto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpAuto2Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addGroup(jpAuto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtplaca, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(22, 22, 22)
                        .addGroup(jpAuto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtmarca, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(29, 29, 29)
                        .addGroup(jpAuto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtcolor, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(jpAuto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jctipoV, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)))
                    .addGroup(jpAuto2Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnExamnV, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jPanel13.add(jpAuto2, "card3");

        jpTicket2.setBackground(new java.awt.Color(1, 187, 246));

        jLabel20.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("ID TICKET:");

        textid_ticket.setEditable(false);
        textid_ticket.setBackground(new java.awt.Color(1, 187, 246));
        textid_ticket.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        textid_ticket.setForeground(new java.awt.Color(255, 255, 255));
        textid_ticket.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textid_ticket.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel21.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("ID ZONA:");

        ComboBoxid_zona.setBackground(new java.awt.Color(1, 187, 246));
        ComboBoxid_zona.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        ComboBoxid_zona.setForeground(new java.awt.Color(255, 255, 255));
        ComboBoxid_zona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR" }));

        jLabel22.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText(" FECHA:");

        jLabel23.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("HORA:");

        labelfecha.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        labelfecha.setForeground(new java.awt.Color(255, 255, 255));
        labelfecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        labelhora.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        labelhora.setForeground(new java.awt.Color(255, 255, 255));
        labelhora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jPanel10.setBackground(new java.awt.Color(9, 122, 253));
        jPanel10.setToolTipText("");

        jLabel25.setBackground(new java.awt.Color(9, 122, 253));
        jLabel25.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SDAV/Vista/Iconos/icons8_ticket_100px.png"))); // NOI18N
        jLabel25.setText("TICKET");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(jLabel25)
                .addContainerGap(236, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 54, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout jpTicket2Layout = new javax.swing.GroupLayout(jpTicket2);
        jpTicket2.setLayout(jpTicket2Layout);
        jpTicket2Layout.setHorizontalGroup(
            jpTicket2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpTicket2Layout.createSequentialGroup()
                .addGroup(jpTicket2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpTicket2Layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabel21)
                        .addGap(31, 31, 31)
                        .addComponent(ComboBoxid_zona, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpTicket2Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jLabel22)
                        .addGap(38, 38, 38)
                        .addComponent(labelfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpTicket2Layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jLabel23)
                        .addGap(40, 40, 40)
                        .addComponent(labelhora, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpTicket2Layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jLabel20)
                        .addGap(30, 30, 30)
                        .addComponent(textid_ticket, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jpTicket2Layout.setVerticalGroup(
            jpTicket2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTicket2Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(jpTicket2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textid_ticket, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jpTicket2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpTicket2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ComboBoxid_zona, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jpTicket2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jpTicket2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelhora, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel13.add(jpTicket2, "card4");

        jpConfirmacion2.setBackground(new java.awt.Color(1, 187, 246));

        jPanel14.setBackground(new java.awt.Color(9, 122, 253));
        jPanel14.setToolTipText("");

        jLabel26.setBackground(new java.awt.Color(9, 122, 253));
        jLabel26.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SDAV/Vista/Iconos/icons8_checkmark_64px_1.png"))); // NOI18N
        jLabel26.setText("CONFIRMACION");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(200, Short.MAX_VALUE)
                .addComponent(jLabel26)
                .addGap(174, 174, 174))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DATOS FINALES");

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CÉDULA:");

        jLabel24.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("PLACA:");

        jLabel27.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("ID TICKET:");

        jLabel28.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("HORA:");

        jLabel29.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText(" FECHA:");

        lch.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        lch.setForeground(new java.awt.Color(255, 255, 255));
        lch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lcc1.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        lcc1.setForeground(new java.awt.Color(255, 255, 255));
        lcc1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lcp1.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        lcp1.setForeground(new java.awt.Color(255, 255, 255));
        lcp1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lct.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        lct.setForeground(new java.awt.Color(255, 255, 255));
        lct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lcf.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        lcf.setForeground(new java.awt.Color(255, 255, 255));
        lcf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lcf.setToolTipText("");

        javax.swing.GroupLayout jpConfirmacion2Layout = new javax.swing.GroupLayout(jpConfirmacion2);
        jpConfirmacion2.setLayout(jpConfirmacion2Layout);
        jpConfirmacion2Layout.setHorizontalGroup(
            jpConfirmacion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jpConfirmacion2Layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jpConfirmacion2Layout.createSequentialGroup()
                .addGroup(jpConfirmacion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpConfirmacion2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lcp1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpConfirmacion2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lcc1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)))
                .addGroup(jpConfirmacion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpConfirmacion2Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel28)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpConfirmacion2Layout.createSequentialGroup()
                        .addGroup(jpConfirmacion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel29)
                            .addComponent(jLabel27))
                        .addGap(18, 18, 18)))
                .addGroup(jpConfirmacion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lct, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lcf, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lch, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jpConfirmacion2Layout.setVerticalGroup(
            jpConfirmacion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpConfirmacion2Layout.createSequentialGroup()
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(jpConfirmacion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpConfirmacion2Layout.createSequentialGroup()
                        .addComponent(lcc1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))
                    .addGroup(jpConfirmacion2Layout.createSequentialGroup()
                        .addGroup(jpConfirmacion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lct, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpConfirmacion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(47, 47, 47)))
                .addGroup(jpConfirmacion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpConfirmacion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lcf, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jpConfirmacion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpConfirmacion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lch, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jpConfirmacion2Layout.createSequentialGroup()
                            .addComponent(lcp1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(53, 53, 53)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jPanel13.add(jpConfirmacion2, "card5");

        getContentPane().add(jPanel13, java.awt.BorderLayout.CENTER);

        jPanel12.setBackground(new java.awt.Color(102, 102, 102));
        jPanel12.setPreferredSize(new java.awt.Dimension(902, 70));
        jPanel12.setRequestFocusEnabled(false);

        btCancel.setBackground(new java.awt.Color(255, 51, 51));
        btCancel.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        btCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SDAV/Vista/Iconos/icons8_cancel_40px.png"))); // NOI18N
        btCancel.setText("CANCELAR");

        btNext.setBackground(new java.awt.Color(9, 122, 253));
        btNext.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        btNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SDAV/Vista/Iconos/icons8_next_page_40px.png"))); // NOI18N
        btNext.setText("SIGUIENTE");

        btBack.setBackground(new java.awt.Color(255, 153, 51));
        btBack.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        btBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SDAV/Vista/Iconos/icons8_back_to_40px.png"))); // NOI18N
        btBack.setText("ATRAS");

        txtNumpanel.setText("0");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btCancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 420, Short.MAX_VALUE)
                .addComponent(txtNumpanel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btBack, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btNext, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btNext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNumpanel))
                .addContainerGap())
        );

        getContentPane().add(jPanel12, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExamnVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExamnVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExamnVActionPerformed
    
    /**
     * @param args the command line arguments
     */

    public JTextField getApell() {
        return apell;
    }

    public void setApell(JTextField apell) {
        this.apell = apell;
    }

    public JButton getBtBack() {
        return btBack;
    }

    public void setBtBack(JButton btBack) {
        this.btBack = btBack;
    }

    public JButton getBtCancel() {
        return btCancel;
    }

    public void setBtCancel(JButton btCancel) {
        this.btCancel = btCancel;
    }

    public JButton getBtNext() {
        return btNext;
    }

    public void setBtNext(JButton btNext) {
        this.btNext = btNext;
    }

    public JButton getBtnExamnV() {
        return btnExamnV;
    }

    public void setBtnExamnV(JButton btnExamnV) {
        this.btnExamnV = btnExamnV;
    }

    public JTextField getDireccion() {
        return direccion;
    }

    public void setDireccion(JTextField direccion) {
        this.direccion = direccion;
    }

    public JTextField getId() {
        return id;
    }

    public void setId(JTextField id) {
        this.id = id;
    }

    public JLabel getLabelfecha() {
        return labelfecha;
    }

    public void setLabelfecha(JLabel labelfecha) {
        this.labelfecha = labelfecha;
    }

    public JLabel getLabelhora() {
        return labelhora;
    }

    public void setLabelhora(JLabel labelhora) {
        this.labelhora = labelhora;
    }

    public JTextField getTextid_ticket() {
        return textid_ticket;
    }

    public void setTextid_ticket(JTextField textid_ticket) {
        this.textid_ticket = textid_ticket;
    }


    public JComboBox<String> getJctipoV() {
        return jctipoV;
    }

    public void setJctipoV(JComboBox<String> jctipoV) {
        this.jctipoV = jctipoV;
    }

    public JPanel getJoLAuto() {
        return joLAuto;
    }

    public void setJoLAuto(JPanel joLAuto) {
        this.joLAuto = joLAuto;
    }

    public JPanel getJpAuto2() {
        return jpAuto2;
    }

    public void setJpAuto2(JPanel jpAuto2) {
        this.jpAuto2 = jpAuto2;
    }

    public JPanel getJpCliente2() {
        return jpCliente2;
    }

    public void setJpCliente2(JPanel jpCliente2) {
        this.jpCliente2 = jpCliente2;
    }

    public JPanel getJpConfirmacion2() {
        return jpConfirmacion2;
    }

    public void setJpConfirmacion2(JPanel jpConfirmacion2) {
        this.jpConfirmacion2 = jpConfirmacion2;
    }

    public JPanel getJpLCliente() {
        return jpLCliente;
    }

    public void setJpLCliente(JPanel jpLCliente) {
        this.jpLCliente = jpLCliente;
    }

    public JPanel getJpLConfirmacion() {
        return jpLConfirmacion;
    }

    public void setJpLConfirmacion(JPanel jpLConfirmacion) {
        this.jpLConfirmacion = jpLConfirmacion;
    }

    public JPanel getJpLTicket() {
        return jpLTicket;
    }

    public void setJpLTicket(JPanel jpLTicket) {
        this.jpLTicket = jpLTicket;
    }

    public JPanel getJpTicket2() {
        return jpTicket2;
    }

    public void setJpTicket2(JPanel jpTicket2) {
        this.jpTicket2 = jpTicket2;
    }

    public JLabel getLblFoto() {
        return lblFoto;
    }

    public void setLblFoto(JLabel lblFoto) {
        this.lblFoto = lblFoto;
    }

    public JTextField getNom() {
        return nom;
    }

    public void setNom(JTextField nom) {
        this.nom = nom;
    }

    public JTextField getTel() {
        return tel;
    }

    public void setTel(JTextField tel) {
        this.tel = tel;
    }

    public JTextField getTxtcolor() {
        return txtcolor;
    }

    public void setTxtcolor(JTextField txtcolor) {
        this.txtcolor = txtcolor;
    }

    public JTextField getTxtmarca() {
        return txtmarca;
    }

    public void setTxtmarca(JTextField txtmarca) {
        this.txtmarca = txtmarca;
    }

    public JTextField getTxtplaca() {
        return txtplaca;
    }

    public void setTxtplaca(JTextField txtplaca) {
        this.txtplaca = txtplaca;
    }

    public JLabel getTxtNumpanel() {
        return txtNumpanel;
    }

    public void setTxtNumpanel(JLabel txtNumpanel) {
        this.txtNumpanel = txtNumpanel;
    }

    public JComboBox<String> getComboBoxid_zona() {
        return ComboBoxid_zona;
    }

    public void setComboBoxid_zona(JComboBox<String> ComboBoxid_zona) {
        this.ComboBoxid_zona = ComboBoxid_zona;
    }

    public JLabel getLcc1() {
        return lcc1;
    }

    public void setLcc1(JLabel lcc1) {
        this.lcc1 = lcc1;
    }

    public JLabel getLcf() {
        return lcf;
    }

    public void setLcf(JLabel lcf) {
        this.lcf = lcf;
    }

    public JLabel getLch() {
        return lch;
    }

    public void setLch(JLabel lch) {
        this.lch = lch;
    }

    public JLabel getLcp1() {
        return lcp1;
    }

    public void setLcp1(JLabel lcp1) {
        this.lcp1 = lcp1;
    }

    public JLabel getLct() {
        return lct;
    }

    public void setLct(JLabel lct) {
        this.lct = lct;
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxid_zona;
    private javax.swing.JTextField apell;
    private javax.swing.JButton btBack;
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btNext;
    private javax.swing.JButton btnExamnV;
    private javax.swing.JTextField direccion;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JComboBox<String> jctipoV;
    private javax.swing.JPanel joLAuto;
    private javax.swing.JPanel jpAuto2;
    private javax.swing.JPanel jpCliente2;
    private javax.swing.JPanel jpConfirmacion2;
    private javax.swing.JPanel jpLCliente;
    private javax.swing.JPanel jpLConfirmacion;
    private javax.swing.JPanel jpLTicket;
    private javax.swing.JPanel jpTicket2;
    private javax.swing.JLabel labelfecha;
    private javax.swing.JLabel labelhora;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lcc1;
    private javax.swing.JLabel lcf;
    private javax.swing.JLabel lch;
    private javax.swing.JLabel lcp1;
    private javax.swing.JLabel lct;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField tel;
    private javax.swing.JTextField textid_ticket;
    private javax.swing.JLabel txtNumpanel;
    private javax.swing.JTextField txtcolor;
    private javax.swing.JTextField txtmarca;
    private javax.swing.JTextField txtplaca;
    // End of variables declaration//GEN-END:variables
}
